name: Alerts to Discord

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🚀 Novo commit ou merge no repositório!"}' \
          $DISCORD_WEBHOOK
